export const TEAMS = [
  // EAST
  { name: 'Duke Blue Devils', abbr: 'DUKE', conf: 'ACC', seed: 1, wins: 32, losses: 2, emoji: '😈', last10: '9-1', region: 'East',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/150.png',
    pace: 72.1, oRtg: 121.4, dRtg: 91.2, eFG: 57.8, tovPct: 13.2, tsPct: 61.2, orbPct: 33.1, ftRate: 38.4,
    roster: [
      { name: 'Cameron Boozer',  pos: 'C',  impact: 8.5, offImpact: 4.2, defImpact: 4.3 },
      { name: 'Isaiah Evans',    pos: 'SG', impact: 5.8, offImpact: 3.2, defImpact: 2.6 },
      { name: 'Darren Harris',   pos: 'PG', impact: 5.1, offImpact: 3.4, defImpact: 1.7 },
      { name: 'Patrick Ngongba', pos: 'PF', impact: 4.2, offImpact: 2.1, defImpact: 2.1 },
      { name: 'Maliq Brown',     pos: 'SF', impact: 3.4, offImpact: 1.6, defImpact: 1.8 },
    ],
  },
  { name: 'UMBC Retrievers', abbr: 'UMBC', conf: 'America East', seed: 16, wins: 18, losses: 15, emoji: '🐕', last10: '5-5', region: 'East',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2437.png',
    pace: 68.2, oRtg: 102.1, dRtg: 108.4, eFG: 48.2, tovPct: 16.1, tsPct: 52.1, orbPct: 27.4, ftRate: 31.2,
    roster: [
      { name: 'Marcus Smith',   pos: 'PG', impact: 6.1, offImpact: 3.8, defImpact: 2.3 },
      { name: 'Jordan Davis',   pos: 'SG', impact: 4.8, offImpact: 2.9, defImpact: 1.9 },
      { name: 'Tyler Brown',    pos: 'SF', impact: 4.2, offImpact: 2.4, defImpact: 1.8 },
      { name: 'Chris Johnson',  pos: 'PF', impact: 3.6, offImpact: 1.8, defImpact: 1.8 },
      { name: 'Kevin Williams', pos: 'C',  impact: 3.1, offImpact: 1.5, defImpact: 1.6 },
    ],
  },
  { name: 'UConn Huskies', abbr: 'CONN', conf: 'Big East', seed: 2, wins: 29, losses: 5, emoji: '🐕', last10: '8-2', region: 'East',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/41.png',
    pace: 67.4, oRtg: 115.2, dRtg: 89.6, eFG: 53.1, tovPct: 12.4, tsPct: 57.8, orbPct: 27.9, ftRate: 32.8,
    roster: [
      { name: 'Liam McNeeley',  pos: 'SF', impact: 7.0, offImpact: 4.0, defImpact: 3.0 },
      { name: 'Aidan Mahaney',  pos: 'PG', impact: 6.2, offImpact: 3.9, defImpact: 2.3 },
      { name: 'Solomon Ball',   pos: 'SG', impact: 5.1, offImpact: 2.9, defImpact: 2.2 },
      { name: 'Samson Johnson', pos: 'C',  impact: 4.7, offImpact: 2.2, defImpact: 2.5 },
      { name: 'Jaylin Stewart', pos: 'PF', impact: 3.2, offImpact: 1.8, defImpact: 1.4 },
    ],
  },
  { name: 'North Carolina', abbr: 'UNC', conf: 'ACC', seed: 5, wins: 24, losses: 8, emoji: '🐏', last10: '6-4', region: 'East',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/153.png',
    pace: 75.2, oRtg: 116.1, dRtg: 97.8, eFG: 55.2, tovPct: 15.8, tsPct: 58.6, orbPct: 32.4, ftRate: 38.8,
    roster: [
      { name: 'Elliot Cadeau',    pos: 'PG', impact: 6.8, offImpact: 4.1, defImpact: 2.7 },
      { name: 'Jalen Washington', pos: 'C',  impact: 5.7, offImpact: 2.8, defImpact: 2.9 },
      { name: 'Ian Jackson',      pos: 'SG', impact: 5.4, offImpact: 3.5, defImpact: 1.9 },
      { name: 'James Rojas',      pos: 'SF', impact: 4.0, offImpact: 2.4, defImpact: 1.6 },
      { name: 'Seth Trimble',     pos: 'PF', impact: 3.3, offImpact: 1.9, defImpact: 1.4 },
    ],
  },
  { name: 'VCU Rams', abbr: 'VCU', conf: 'A-10', seed: 11, wins: 27, losses: 7, emoji: '🏙️', last10: '7-3', region: 'East',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2670.png',
    pace: 70.1, oRtg: 112.8, dRtg: 90.9, eFG: 51.8, tovPct: 13.4, tsPct: 55.9, orbPct: 30.7, ftRate: 36.8,
    roster: [
      { name: 'Max Shulga',         pos: 'PG', impact: 6.4, offImpact: 3.9, defImpact: 2.5 },
      { name: 'Zeb Jackson',        pos: 'SG', impact: 5.2, offImpact: 3.1, defImpact: 2.1 },
      { name: 'Joe Bamisile',       pos: 'SF', impact: 4.8, offImpact: 3.0, defImpact: 1.8 },
      { name: 'Jamir Watkins',      pos: 'PF', impact: 4.3, offImpact: 2.3, defImpact: 2.0 },
      { name: 'Babatunde Durodola', pos: 'C',  impact: 3.8, offImpact: 1.8, defImpact: 2.0 },
    ],
  },
  // WEST
  { name: 'Arizona Wildcats', abbr: 'ARIZ', conf: 'Big 12', seed: 1, wins: 32, losses: 2, emoji: '🐱', last10: '9-1', region: 'West',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/12.png',
    pace: 74.6, oRtg: 119.8, dRtg: 93.4, eFG: 55.9, tovPct: 14.1, tsPct: 59.8, orbPct: 30.4, ftRate: 36.1,
    roster: [
      { name: 'Trey Kirby',    pos: 'PG', impact: 7.9, offImpact: 4.8, defImpact: 3.1 },
      { name: 'Henri Veesaar', pos: 'C',  impact: 5.4, offImpact: 2.6, defImpact: 2.8 },
      { name: 'Jaden Bradley', pos: 'SG', impact: 5.1, offImpact: 3.2, defImpact: 1.9 },
      { name: 'KJ Lewis',      pos: 'SF', impact: 4.3, offImpact: 2.5, defImpact: 1.8 },
      { name: 'Anthony Dell',  pos: 'PF', impact: 3.0, offImpact: 1.6, defImpact: 1.4 },
    ],
  },
  { name: 'LIU Sharks', abbr: 'LIU', conf: 'NEC', seed: 16, wins: 20, losses: 13, emoji: '🦈', last10: '6-4', region: 'West',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2363.png',
    pace: 69.1, oRtg: 103.4, dRtg: 109.2, eFG: 47.8, tovPct: 17.2, tsPct: 51.4, orbPct: 28.1, ftRate: 30.8,
    roster: [
      { name: 'Darius King',   pos: 'PG', impact: 5.8, offImpact: 3.6, defImpact: 2.2 },
      { name: 'Malik Stone',   pos: 'SG', impact: 4.6, offImpact: 2.8, defImpact: 1.8 },
      { name: 'James Reed',    pos: 'SF', impact: 4.0, offImpact: 2.2, defImpact: 1.8 },
      { name: 'Tyler Grant',   pos: 'PF', impact: 3.4, offImpact: 1.7, defImpact: 1.7 },
      { name: 'Chris Adams',   pos: 'C',  impact: 3.0, offImpact: 1.4, defImpact: 1.6 },
    ],
  },
  { name: 'Wisconsin Badgers', abbr: 'WIS', conf: 'Big Ten', seed: 5, wins: 24, losses: 10, emoji: '🦡', last10: '6-4', region: 'West',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/275.png',
    pace: 64.2, oRtg: 112.4, dRtg: 93.1, eFG: 52.8, tovPct: 12.1, tsPct: 56.4, orbPct: 27.2, ftRate: 33.6,
    roster: [
      { name: 'John Blackwell', pos: 'PG', impact: 6.8, offImpact: 4.1, defImpact: 2.7 },
      { name: 'Nolan Winter',   pos: 'C',  impact: 5.6, offImpact: 2.6, defImpact: 3.0 },
      { name: 'Kamari McGee',   pos: 'SG', impact: 5.2, offImpact: 3.3, defImpact: 1.9 },
      { name: 'Max Klesmit',    pos: 'SF', impact: 4.4, offImpact: 2.8, defImpact: 1.6 },
      { name: 'Steven Crowl',   pos: 'PF', impact: 3.8, offImpact: 2.0, defImpact: 1.8 },
    ],
  },
  { name: 'Arkansas Razorbacks', abbr: 'ARK', conf: 'SEC', seed: 4, wins: 26, losses: 8, emoji: '🐗', last10: '6-4', region: 'West',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/8.png',
    pace: 73.8, oRtg: 115.6, dRtg: 96.4, eFG: 53.9, tovPct: 15.1, tsPct: 57.4, orbPct: 31.6, ftRate: 39.2,
    roster: [
      { name: 'Adou Thiero',     pos: 'SF', impact: 6.7, offImpact: 3.8, defImpact: 2.9 },
      { name: 'Zvonimir Ivisic', pos: 'C',  impact: 5.8, offImpact: 2.9, defImpact: 2.9 },
      { name: 'D.J. Wagner',     pos: 'PG', impact: 5.4, offImpact: 3.6, defImpact: 1.8 },
      { name: 'Boogie Fland',    pos: 'SG', impact: 4.9, offImpact: 3.3, defImpact: 1.6 },
      { name: 'Trevon Brazile',  pos: 'PF', impact: 3.4, offImpact: 1.8, defImpact: 1.6 },
    ],
  },
  { name: 'Gonzaga Bulldogs', abbr: 'GONZ', conf: 'WCC', seed: 3, wins: 30, losses: 3, emoji: '🐶', last10: '8-2', region: 'West',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2250.png',
    pace: 76.3, oRtg: 118.9, dRtg: 94.7, eFG: 56.4, tovPct: 15.3, tsPct: 60.1, orbPct: 31.8, ftRate: 40.2,
    roster: [
      { name: 'Ryan Nembhard',  pos: 'PG', impact: 7.4, offImpact: 4.6, defImpact: 2.8 },
      { name: 'Graham Ike',     pos: 'C',  impact: 6.8, offImpact: 3.8, defImpact: 3.0 },
      { name: 'Braden Huff',    pos: 'PF', impact: 5.2, offImpact: 2.9, defImpact: 2.3 },
      { name: 'Dusty Stromer',  pos: 'SG', impact: 4.1, offImpact: 2.8, defImpact: 1.3 },
      { name: 'Ben Gregg',      pos: 'SF', impact: 3.4, offImpact: 1.9, defImpact: 1.5 },
    ],
  },
  { name: 'Purdue Boilermakers', abbr: 'PUR', conf: 'Big Ten', seed: 2, wins: 27, losses: 8, emoji: '🚂', last10: '6-4', region: 'West',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png',
    pace: 69.8, oRtg: 116.2, dRtg: 92.1, eFG: 54.6, tovPct: 13.8, tsPct: 58.2, orbPct: 29.4, ftRate: 36.8,
    roster: [
      { name: 'Braden Smith',   pos: 'PG', impact: 7.6, offImpact: 4.4, defImpact: 3.2 },
      { name: 'Zach Edey',      pos: 'C',  impact: 6.9, offImpact: 3.8, defImpact: 3.1 },
      { name: 'Fletcher Loyer', pos: 'SG', impact: 5.3, offImpact: 3.4, defImpact: 1.9 },
      { name: 'Mason Gillis',   pos: 'PF', impact: 4.1, offImpact: 2.2, defImpact: 1.9 },
      { name: 'Lance Jones',    pos: 'SF', impact: 3.6, offImpact: 2.0, defImpact: 1.6 },
    ],
  },
  // SOUTH
  { name: 'Florida Gators', abbr: 'FLA', conf: 'SEC', seed: 1, wins: 26, losses: 7, emoji: '🐊', last10: '7-3', region: 'South',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/57.png',
    pace: 71.2, oRtg: 116.8, dRtg: 95.3, eFG: 54.7, tovPct: 14.6, tsPct: 58.9, orbPct: 30.1, ftRate: 37.1,
    roster: [
      { name: 'Walter Clayton',  pos: 'PG', impact: 7.6, offImpact: 4.8, defImpact: 2.8 },
      { name: 'Alex Condon',     pos: 'C',  impact: 5.5, offImpact: 2.7, defImpact: 2.8 },
      { name: 'Thomas Haugh',    pos: 'PF', impact: 4.8, offImpact: 2.6, defImpact: 2.2 },
      { name: 'Will Richard',    pos: 'SG', impact: 4.4, offImpact: 2.9, defImpact: 1.5 },
      { name: 'Zyon Pullin',     pos: 'SF', impact: 3.2, offImpact: 2.0, defImpact: 1.2 },
    ],
  },
  { name: 'Iowa State Cyclones', abbr: 'ISU', conf: 'Big 12', seed: 2, wins: 27, losses: 7, emoji: '🌪️', last10: '7-3', region: 'South',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/66.png',
    pace: 69.4, oRtg: 114.9, dRtg: 90.4, eFG: 53.4, tovPct: 13.7, tsPct: 57.6, orbPct: 28.2, ftRate: 33.8,
    roster: [
      { name: 'Tamin Lipsey',     pos: 'PG', impact: 6.9, offImpact: 3.8, defImpact: 3.1 },
      { name: 'Milan Momcilovic', pos: 'SF', impact: 6.1, offImpact: 3.9, defImpact: 2.2 },
      { name: 'Dishon Jackson',   pos: 'C',  impact: 5.2, offImpact: 2.4, defImpact: 2.8 },
      { name: 'Keshon Gilbert',   pos: 'SG', impact: 4.6, offImpact: 3.0, defImpact: 1.6 },
      { name: 'Caleb Grill',      pos: 'PF', impact: 2.9, offImpact: 1.5, defImpact: 1.4 },
    ],
  },
  { name: 'Alabama Crimson Tide', abbr: 'ALA', conf: 'SEC', seed: 4, wins: 23, losses: 9, emoji: '🐘', last10: '6-4', region: 'South',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/333.png',
    pace: 72.4, oRtg: 114.2, dRtg: 94.8, eFG: 53.1, tovPct: 14.8, tsPct: 57.1, orbPct: 30.2, ftRate: 37.4,
    roster: [
      { name: 'Mark Sears',    pos: 'PG', impact: 7.4, offImpact: 4.8, defImpact: 2.6 },
      { name: 'Jarin Stevenson',pos:'C',  impact: 5.6, offImpact: 2.7, defImpact: 2.9 },
      { name: 'Aden Holloway', pos: 'SG', impact: 5.1, offImpact: 3.2, defImpact: 1.9 },
      { name: 'Grant Nelson',  pos: 'PF', impact: 4.8, offImpact: 2.5, defImpact: 2.3 },
      { name: 'Rylan Griffen', pos: 'SF', impact: 3.4, offImpact: 2.0, defImpact: 1.4 },
    ],
  },
  { name: 'Tennessee Volunteers', abbr: 'TENN', conf: 'SEC', seed: 6, wins: 22, losses: 11, emoji: '🍊', last10: '5-5', region: 'South',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png',
    pace: 68.6, oRtg: 113.1, dRtg: 92.4, eFG: 52.4, tovPct: 13.1, tsPct: 56.8, orbPct: 28.9, ftRate: 34.2,
    roster: [
      { name: 'Zakai Zeigler',  pos: 'PG', impact: 7.1, offImpact: 4.0, defImpact: 3.1 },
      { name: 'Felix Okpara',   pos: 'C',  impact: 5.8, offImpact: 2.5, defImpact: 3.3 },
      { name: 'Jordan Gainey',  pos: 'SG', impact: 5.0, offImpact: 3.1, defImpact: 1.9 },
      { name: 'Igor Milicic',   pos: 'PF', impact: 4.4, offImpact: 2.3, defImpact: 2.1 },
      { name: 'Cade Phillips',  pos: 'SF', impact: 3.2, offImpact: 1.8, defImpact: 1.4 },
    ],
  },
  // MIDWEST
  { name: 'Michigan Wolverines', abbr: 'MICH', conf: 'Big Ten', seed: 1, wins: 31, losses: 3, emoji: '🐺', last10: '8-2', region: 'Midwest',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/130.png',
    pace: 68.9, oRtg: 117.6, dRtg: 92.8, eFG: 54.2, tovPct: 12.8, tsPct: 58.4, orbPct: 28.7, ftRate: 34.2,
    roster: [
      { name: 'Nimari Burnett', pos: 'SG', impact: 7.2, offImpact: 4.1, defImpact: 3.1 },
      { name: 'Vlad Goldin',    pos: 'C',  impact: 6.1, offImpact: 3.0, defImpact: 3.1 },
      { name: 'Tre Donaldson',  pos: 'PG', impact: 5.3, offImpact: 3.4, defImpact: 1.9 },
      { name: 'Danny Wolf',     pos: 'PF', impact: 4.8, offImpact: 2.8, defImpact: 2.0 },
      { name: 'Sam Walters',    pos: 'SF', impact: 3.1, offImpact: 1.7, defImpact: 1.4 },
    ],
  },
  { name: 'Texas Tech Red Raiders', abbr: 'TTU', conf: 'Big 12', seed: 5, wins: 22, losses: 10, emoji: '🔫', last10: '6-4', region: 'Midwest',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png',
    pace: 67.8, oRtg: 112.6, dRtg: 91.8, eFG: 51.9, tovPct: 13.2, tsPct: 56.1, orbPct: 29.1, ftRate: 34.8,
    roster: [
      { name: 'Darrion Williams', pos: 'SF', impact: 6.9, offImpact: 3.9, defImpact: 3.0 },
      { name: 'Chance McMillian', pos: 'PG', impact: 5.8, offImpact: 3.6, defImpact: 2.2 },
      { name: 'Warren Washington',pos: 'C',  impact: 5.3, offImpact: 2.6, defImpact: 2.7 },
      { name: 'Pop Isaacs',       pos: 'SG', impact: 4.8, offImpact: 3.1, defImpact: 1.7 },
      { name: 'Kevin Obanor',     pos: 'PF', impact: 3.6, offImpact: 1.9, defImpact: 1.7 },
    ],
  },
  { name: 'Kansas Jayhawks', abbr: 'KU', conf: 'Big 12', seed: 4, wins: 23, losses: 10, emoji: '🦅', last10: '6-4', region: 'Midwest',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/2305.png',
    pace: 70.6, oRtg: 113.2, dRtg: 93.8, eFG: 52.4, tovPct: 14.3, tsPct: 56.8, orbPct: 29.8, ftRate: 35.4,
    roster: [
      { name: 'Hunter Dickinson', pos: 'C',  impact: 7.8, offImpact: 4.2, defImpact: 3.6 },
      { name: 'Dajuan Harris',    pos: 'PG', impact: 5.6, offImpact: 3.1, defImpact: 2.5 },
      { name: 'KJ Adams',         pos: 'PF', impact: 4.9, offImpact: 2.6, defImpact: 2.3 },
      { name: 'AJ Storr',         pos: 'SG', impact: 4.4, offImpact: 3.0, defImpact: 1.4 },
      { name: 'Shakeel Moore',    pos: 'SF', impact: 3.1, offImpact: 1.6, defImpact: 1.5 },
    ],
  },
  { name: 'Houston Cougars', abbr: 'HOU', conf: 'Big 12', seed: 3, wins: 28, losses: 6, emoji: '🐆', last10: '7-3', region: 'Midwest',
    logo: 'https://a.espncdn.com/i/teamlogos/ncaa/500/248.png',
    pace: 65.8, oRtg: 113.4, dRtg: 88.1, eFG: 51.6, tovPct: 11.9, tsPct: 56.2, orbPct: 29.4, ftRate: 35.6,
    roster: [
      { name: "L.J. Cryer",      pos: 'SG', impact: 6.8, offImpact: 4.4, defImpact: 2.4 },
      { name: "Ja'Vier Francis",  pos: 'C',  impact: 5.9, offImpact: 2.6, defImpact: 3.3 },
      { name: 'Emanuel Sharp',   pos: 'SF', impact: 5.2, offImpact: 3.1, defImpact: 2.1 },
      { name: 'Damian Dunn',     pos: 'PG', impact: 4.4, offImpact: 2.9, defImpact: 1.5 },
      { name: 'Joseph Tugler',   pos: 'PF', impact: 3.6, offImpact: 1.6, defImpact: 2.0 },
    ],
  },
]

export const MATCHUPS = [
  { id: 1, region: 'East',    home: 'DUKE', away: 'UMBC',  time: 'Jeu 19 Mar' },
  { id: 2, region: 'East',    home: 'CONN', away: 'UNC',   time: 'Ven 20 Mar' },
  { id: 3, region: 'East',    home: 'UNC',  away: 'VCU',   time: 'Ven 20 Mar' },
  { id: 4, region: 'West',    home: 'ARIZ', away: 'LIU',   time: 'Ven 20 Mar' },
  { id: 5, region: 'West',    home: 'WIS',  away: 'ARK',   time: 'Jeu 19 Mar' },
  { id: 6, region: 'West',    home: 'GONZ', away: 'PUR',   time: 'Jeu 19 Mar' },
  { id: 7, region: 'South',   home: 'FLA',  away: 'ISU',   time: 'Ven 20 Mar' },
  { id: 8, region: 'South',   home: 'ALA',  away: 'TENN',  time: 'Ven 20 Mar' },
  { id: 9, region: 'Midwest', home: 'MICH', away: 'TTU',   time: 'Jeu 19 Mar' },
  { id: 10, region: 'Midwest', home: 'KU',  away: 'HOU',   time: 'Ven 20 Mar' },
]
